version: "3.3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: "mysql"
    hostname: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
